apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Daemon       off
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*

    [FILTER]
        Name              kubernetes
        Match             kube.*
        Kube_Tag_Prefix   kube.var.log.containers.
        Merge_Log         On
        Keep_Log          Off

        #    [FILTER]
        #Name              grep
        #Match             kube.*
        #Regex             container_name  project-udacity-3


    [OUTPUT]
        Name              cloudwatch_logs
        Match             *
        region            us-east-1
        log_group_name    udacity-app-logs
        auto_create_group true
        log_stream_prefix project-udacity-  #this will create an event stream in AWS console cloud wath example - project-udacity-kube.var.log.containers.project-udacity-3-5d4cb7795c-t27gm_default_health-logger-82318fbf34f0407710e663cf587959458eb3a109eaabb8917fff8a486470e03f.log
